name: base
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  get_it:
  flutter_bloc:
  flutter_i18n:
  hive:
  flutter_secure_storage:
  path_provider:
  equatable:
  global_configuration: 
  dio:
  connectivity_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator: 
    
flutter:
  generate: false
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/cfg/